School/urls.py
from django.contrib import admin
from django.urls import path
from Academic import views
urlpatterns = [
    path('', views.index, name='index'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('admin/', admin.site.urls),
]

Academic/models.py
from django.db import models


class Rol(models.Model):
    rol = models.CharField(max_length=140)

    def __str__(self):
        return "%s" % (self.rol)


class Jornada(models.Model):
    jornada = models.CharField(max_length=5)

    def __str__(self):
        return "%s" % (self.jornada)


class Personal(models.Model):
    apellidos = models.CharField(max_length=200)
    nombres = models.CharField(max_length=140)
    tipo_documento_personal = models.CharField(max_length=5)
    documento_personal = models.BigIntegerField()
    titulo_personal = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    telefonoCell = models.CharField(max_length=15)
    rol = models.ForeignKey(Rol, on_delete=models.CASCADE,)
    jornada = models.ForeignKey(Jornada, on_delete=models.CASCADE,)

    class Meta:
        unique_together = (('email',),)

    def save(self, force_insert=False, force_update=False):
        self.apellidos = self.apellidos.upper()
        self.nombres = self.nombres.upper()
        super(Personal, self).save(force_insert, force_update)

    def __str__(self):
        return "%s - %s" % (self.nombres, self.apellidos)


class Grado(models.Model):
    grado = models.CharField(max_length=200)
    jornada = models.ForeignKey(Jornada, on_delete=models.CASCADE,)
    personal = models.ManyToManyField(Personal)

    def __str__(self):
        return"%s" % (self.grado)

Academic/forms.py
from django import forms
from .models import Personal


class PersonalForm(forms.ModelForm):
    class Meta:
        model = Personal
        fields = "__all__"

Academic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Personal, Rol, Jornada
from .forms import PersonalForm
from django.views.generic import ListView, DetailView
from django.template.context import RequestContext
from django.contrib import messages
from django.http import JsonResponse, HttpResponseRedirect


def index(request):
    template_name = 'index.html'
    context_object_name = 'contact_list'
    if request.method == 'POST':
        fromPersonal = PersonalForm(request.POST)
        if fromPersonal.is_valid():
            fromPersonal.save()
            messages.success(request, 'registro Exitoso !!',
                             extra_tags='alert alert-success')
        else:
            messages.warning(request, 'Debe completar los campos',
                             extra_tags='alert alert-danger')

    fromPesonal = PersonalForm()
    dataPersonal = Personal.objects.all()
    rols = Rol.objects.all()
    jornadas = Jornada.objects.all()
    return render(request, template_name, locals())


def update(request):
    if request.method == 'POST':
        personal = Personal.objects.get(pk=request.POST['pk'])
        personal.nombres = request.POST['nombres']
        personal.apellidos = request.POST['apellidos']
        personal.tipo_documento_personal = request.POST['tipo_documento_personal']
        personal.documento_personal = request.POST['documento_personal']
        personal.titulo_personal = request.POST['titulo_personal']
        personal.email = request.POST['email']
        personal.telefonoCell = request.POST['telefonoCell']
        personal.rol = request.POST['rol']
        personal.jornada = request.POST['jornada']
        personal.save()
        messages.success(request, 'registro actualizado Exitoso !!',
                         extra_tags='alert alert-success')
    return HttpResponseRedirect("/")


def delete(request):
    if request.method == 'POST':
        template_name = 'index.html'
        context_object_name = 'contact_list'
        personal = Personal.objects.get(pk=request.POST['pk'])
        if personal:
            personal.delete()
        else:
            messages.warning(request, 'Id no encontrado',
                             extra_tags='alert alert-danger')
        fromPesonal = PersonalForm()
        dataPersonal = Personal.objects.all()
        messages.success(request, 'registro Eliminado !!',
                         extra_tags='alert alert-success')
        return HttpResponseRedirect("/")

Academic/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div class="container-fluid">
{% if messages %}
      {% for message in messages %}
      	<div{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
      {% endfor %}
  
{% endif %}	

<form class="row g-3" method='POST'>
{% csrf_token %}
<table class="table">
<thead>
    <tr>
      <th scope="col">Nombres</th>
      <th scope="col">Apellidos</th>
      <th scope="col">Tipo de Documento</th>
      <th scope="col">Documento</th>
      <th scope="col">titulo Profecional</th>
      <th scope="col">Email</th>
      <th scope="col">telefono celular</th>
      <th scope="col">Rol</th>
      <th scope="col">Jordada</th>
      <th scope="col">Accion</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>{{fromPesonal.nombres}}</th>
      <td>{{fromPesonal.apellidos}}  </td>
      <td>{{fromPesonal.tipo_documento_personal}}</td>
      <td>{{fromPesonal.documento_personal}}</td>
      <td>{{fromPesonal.titulo_personal}}</td>
      <td>{{fromPesonal.email}}</td>
      <td>{{fromPesonal.telefonoCell}}</td>
      <td>{{fromPesonal.rol}}</td>
      <td>{{fromPesonal.jornada}}</td>
      <td><button type="submit" class="btn btn-primary mb-3">Guardar</button></th>
    </tr>
  </tbody>
</tatle>
</form>

</div>
<form class="row g-3" method='POST'>
<table class="table">
<thead>
    <tr>
      <th scope="col">Nombres</th>
      <th scope="col">Apellidos</th>
      <th scope="col">Tipo de Documento</th>
      <th scope="col">Documento</th>
      <th scope="col">titulo Profecional</th>
      <th scope="col">Email</th>
      <th scope="col">telefono celular</th>
      <th scope="col">Rol</th>
      <th scope="col">Jordada</th>
      <th scope="col">Accion</th>
    </tr>
  </thead>
  <tbody>
  {% for persona in dataPersonal %}
    <tr>
      <th><input type="text" name="nombres" maxlength="140" required="" id="id_nombres" value='{{persona.nombres}}'></th>
      <td><input type="text" name="apellidos" maxlength="200" required="" id="id_apellidos" value='{{persona.apellidos}}'>  </td>
      <td><input type="text" name="tipo_documento_personal" maxlength="5" required="" id="id_tipo_documento_personal" value='{{persona.tipo_documento_personal}}'></td>
      <td><input type="number" name="documento_personal" min="-9223372036854775808" max="9223372036854775807" required="" id="id_documento_personal" value='{{persona.documento_personal}}'></td>
      <td><input type="text" name="titulo_personal" maxlength="200" required="" id="id_titulo_personal" value='{{persona.titulo_personal}}'></td>
      <td><input type="email" name="email" maxlength="200" required="" id="id_email" value='{{persona.email}}'></td>
      <td><input type="text" name="telefonoCell" maxlength="15" required="" id="id_telefonoCell" value='{{persona.telefonoCell}}'></td>
      <td><select name="rol" required="" id="id_rol">
        <option value="" selected="">---------</option>
        {% for rol in rols %}
        <option value="{{rol.pk}}" {% if rol.pk == persona.rol.pk %}selected="selected"{% endif %} >{{rol.rol}}</option>
        {% endfor %}

        </select>
    </td>
      <td>
        <select name="jornada" required="" id="id_jornada">
            <option value="" selected="">---------</option>
            {% for jornada in jornadas  %}
            <option value="{{jornada.pk}}" {% if jornada.pk == persona.jornada.pk %}selected="selected"{% endif %} >{{jornada.jornada}}</option>
            {% endfor %}

        </select>
</td>
      <td><button type="submit" class="btn btn-primary mb-3">Actualizar</button></th>
      <td>
      <form action="/delete/" method="post" accept-charset="utf-8">{% csrf_token %}
            <input type="hidden" id="pk" name="pk" value="{{persona.pk}}"> 
 		    <button type="submit" class="btn btn-danger mb-3">Eliminar</button>
 	    </form>
      </th>
    </tr>
    {% endfor %}
  </tbody>
</tatle>
</form>
</body>
</html>